export const ProjectList = [
  {
    name: "Portfolio",
    skills: "ReactJS, JavaScript, CSS, HTML",
    url : "https://ankitsuman.netlify.app/",
    tag: ["featured", "all", "react"],
    description : "My personal portfolio website, meticulously designed and coded from scratch. Embodying a minimalist and modern aesthetic, the tasteful use of colors exudes an alluring charm, creating an aesthetically pleasing user experience. The Project page offers seamless sorting options for effortless navigation through my showcased projects. Leveraging the power of ReactJS, this dynamic portfolio is hosted flawlessly on Netlify.",
  },
  {
    name: "Theme Switcher",
    skills: "ReactJS, JavaScript, CSS, HTML",
    url : "https://switch-themes.netlify.app/",
    tag: ["featured", "all", "react"],
    description : "An intuitive React App featuring a mini-website, designed to offer seamless theme-switching functionality. Elevate your browsing experience by effortlessly toggling through diverse themes using the elegantly placed buttons. Each press artfully transforms the color scheme, imbuing the website with a fresh and captivating appearance. This cutting-edge project exemplifies the seamless integration of design and functionality.",
  },
  {
    name: "Random APIs",
    skills: "ReactJS, JavaScript, CSS, HTML",
    url : "https://random-api-project.netlify.app/",
    tag: ["featured", "all", "react"],
    description : "Step into a world of delightful randomness with this captivating React App, thoughtfully curated to bring moments of joy and amusement. Discover an array of APIs, each encapsulating a unique surprise - from humorous jokes and intriguing trivia to soulful poetry and clever puns. Six APIs lie at your fingertips, waiting to whisk you away on an enchanting journey of discovery.",
  },
  {
    name: "Mix-N-Match Game",
    skills: "JavaScript, CSS, HTML",
    url : "https://js-mix-n-match.netlify.app/",
    tag: ["all", "game"],
    description : "A Memory Game, crafted to challenge your memory prowess. Upon tapping the 'Start' button, embark on an engaging quest to match cards through strategic memory recall. Each card reveals its identity upon tapping. Sharpen your memory as you unveil two cards at a time, striving to find perfect matches. Immerse yourself in this elegantly designed experience, combining entertainment and cognitive exercise in an exquisite fusion of design and functionality.",
  },
  {
    name: "Coffee Shop Landing Page",
    skills: "JavaScript, CSS, HTML",
    url : "https://js-coffeeshop.netlify.app/",
    tag: ["all"],
    description : "An exquisitely designed landing page tailored for a sophisticated Coffee Shop/Cafe. Crafted with a harmonious color scheme that encapsulates the essence of a cozy coffee haven, this aesthetically pleasing page captivates visitors' senses. Thoughtfully curated to showcase the delectable products and premium offerings, it seamlessly delivers essential information for an enriched buying experience.",
  },
  {
    name: "To-Do List",
    skills: "ReactJS, JavaScript, CSS, HTML",
    url : "https://reactjs-todolistapp.netlify.app/",
    tag: ["all", "react"],
    description : "A Todo list app meticulously developed with ReactJS, offering seamless task management with an intuitive interface. This robust application allows users to effortlessly add tasks and efficiently remove completed items. The implementation of unique IDs ensures precise identification, enabling precise removal of targeted tasks, even amidst identical task names.",
  },
  {
    name: "Quote Generator",
    skills: "ReactJS, JavaScript, CSS, HTML",
    url : "https://react-quotegenerator.netlify.app/",
    tag: ["all", "react"],
    description : "A simple Quote Generator app skillfully crafted with ReactJS, seamlessly harnessing the potential of APIs to present captivating and inspirational quotes. This elegantly designed project exemplifies the seamless integration of API technology into a dynamic web application.",
  },
  {
    name: "Rock, Paper, Scissor",
    skills: "JavaScript, CSS, HTML",
    url : "https://js-rockpaperscissorgame.netlify.app/",
    tag: ["all"],
    description: "An elegant and engaging web app that invites users to play the classic game of Rock, Paper, Scissors against the computer. Designed with a focus on minimalism and aesthetics, this delightful experience captivates users with its sleek interface and minimal color scheme. The results of each game are promptly displayed, while the overall score is recorded, creating a seamless and interactive gaming experience.",
  },
  {
    name: "Calculator",
    skills: "JavaScript, CSS, HTML",
    url : "https://js-calculator-projects.netlify.app/",
    tag: ["all"],
    description: "Presenting a sophisticated and visually appealing calculator, skillfully designed using HTML, CSS, and JavaScript. Embodying a sleek and minimalist aesthetic, this calculator boasts all the essential functionalities of a basic calculator, ensuring seamless and accurate calculations. The captivating color scheme draws inspiration from the renowned Google logo palette, elevating the overall user experience.",
  },
  {
    name: "Analog Clock",
    skills: "JavaScript, CSS, HTML",
    url : "https://js-analogclocks.netlify.app/",
    tag: ["all"],
    description: "An elegant and accurate clock crafted using HTML, CSS, and JavaScript. This sleek timepiece fetches the initial time from the user's system and seamlessly updates every second, mirroring the precision of a real clock. With smooth and fluid hand movements, it emulates the charm of a traditional timekeeping device.",
  },
  {
    name: "Expense Tracker",
    skills: "JavaScript, CSS, HTML",
    url : "https://js-expense-tracker-project.netlify.app/",
    tag: ["all"],
    description: "A dynamic expense tracking website designed to efficiently manage your financial data. With intuitive category selection and date setting functionalities, effortlessly keep track of your expenses. The data is stored and showcased in an organized table format, accompanied by a Pie Chart that highlights the distribution of expenses across categories.",
  },
//   {
//     name: "Dashboard Visualizer",
//     image: project,
//     skills: [ReactJS, JS, CSS, HTML],
//     url : "www.google.com",
//     tag: ["featured", "all", "react", "clone"],
//     featured: false,
//     description: "Description",
//   },
  
];